---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: web-app
  namespace: staging
  name: deployment-odoo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: staging-odoo
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: staging-odoo
        application: web-app
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: staging-odoo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: web-app
  namespace: staging
  name: staging-odoo
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: staging-odoo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: staging
  name: ingress-odoo
  annotations:
    alb.ingress.kubernetes.io/subnets: subnet-05f7915a4c078ee2f	, subnet-0639f32ec0dd31944
    alb.ingress.kubernetes.io/security-groups: eks-cluster-sg-newlogic-dev-eks-1672543686 , newlogic-dev-alb-sg
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP 
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:100774766156:certificate/2318e4c1-dd45-489c-a8d0-3c4f7359e53d
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: staging-odoo
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: staging-odoo
              port:
                number: 80
